#!/usr/bin/env perl
use strict;
use warnings;
use Audio::Play::MPG123;
use Config::Simple;
use File::Spec::Functions qw/catfile/;

sub load_config {
    my $rc_file_name = '.with-soundrc';
    my $rc_file_location = catfile( $ENV{HOME}, $rc_file_name );

    # Not exists rc file on home directory.
    unless ( -f $rc_file_location ) {
        die "[ERROR] Please put '$rc_file_name' file on your home directory\n";
    }

    my $config = Config::Simple->new($rc_file_location);
    return $config->param('SUCCESS'), $config->param('FAILURE');
}

sub play_mp3 {
    my ( $mp3_file, $status ) = @_;

    if ( -f $mp3_file ) {
        my $pid = fork;
        die "fork failed." unless defined $pid;

        if ( $pid == 0 ) {
            my $player = Audio::Play::MPG123->new;
            $player->load($mp3_file);
            $player->poll(1) until $player->state == 0;
            exit;
        }
    }
    else {
        warn "[WARNING] Sound file is not specified when $status. "
          . "Please check your .with-soundrc file.\n";
    }
}

die "[ERROR] Please specify command line parameters.\n" unless @ARGV;

my ( $success_sound, $failure_sound ) = load_config;
$success_sound = glob $success_sound;
$failure_sound = glob $failure_sound;

my $retval = system(@ARGV);

if ( $retval == 0 ) {

    # success
    play_mp3( $success_sound, 'success' );
}
else {
    # failure
    play_mp3( $failure_sound, 'failure' );
}

$retval = 1 if $retval > 255;
exit($retval);
__END__
